# Generated by Django 4.1.3 on 2022-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
