# Generated by Django 4.1.3 on 2022-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_users_id_alter_users_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000, serialize=False),
        ),
    ]
