# Generated by Django 4.1.3 on 2023-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_message_imag_users_imag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="imag",
        ),
        migrations.AddField(
            model_name="users",
            name="image",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="users",
            name="nickname",
            field=models.CharField(
                default=models.CharField(
                    max_length=1000, primary_key=True, serialize=False
                ),
                max_length=1000,
            ),
        ),
    ]
